### ISSUE TITLE
Add example with playwright-video

### ISSUE THREAD

**Issue by mxschmitt** [mxschmitt/try-playwright#13]
Add [playwright-video](https://github.com/qawolf/playwright-video) example.

**Comment by arjun27** [comment]
What do you think about running screencast by default for all executions on Chromium (for now)? That way, executions will not need additional screenshots code to verify result of execution.

**Comment by mxschmitt** [comment]
> What do you think about running screencast by default for all executions on Chromium (for now)? That way, executions will not need additional screenshots code to verify result of execution.

Sounds good, for that I would probably need to wrap each `context.newPage()` call somehow. So I can inject there the `playwright-video` call.

**Comment by arjun27** [comment]
Good point. 

Thinking aloud here - what if try-playwright exposes a "context" object to the script (instead of exposing the "playwright" object right now). That way, an existing browser instance could be shared across executions, and since nothing needs to be launched, executions will be much faster. It does have downsides, like `browser.newPage()` cannot be used, and the browser type will need to be specified outside the script (with a dropdown; causing the scripts to be limited to just one browser). With this and https://github.com/qawolf/playwright-video/issues/7, the screencast implementation would be simplified.

Of course this is only an idea, feel free to shoot it down :)

**Comment by mxschmitt** [comment]
> Good point.
> 
> Thinking aloud here - what if try-playwright exposes a "context" object to the script (instead of exposing the "playwright" object right now). That way, an existing browser instance could be shared across executions, and since nothing needs to be launched, executions will be much faster. It does have downsides, like `browser.newPage()` cannot be used, and the browser type will need to be specified outside the script (with a dropdown; causing the scripts to be limited to just one browser). With this and [qawolf/playwright-video#7](https://github.com/qawolf/playwright-video/issues/7), the screencast implementation would be simplified.
> 
> Of course this is only an idea, feel free to shoot it down :)

awesome idea!

**Comment by jperl** [comment]
We will add captureAllPages as soon as https://github.com/microsoft/playwright/pull/1163 is merged

**Comment by mxschmitt** [comment]
@jperl 
fyi: I've not implemented the approach to always record chromium sessions, because it does probably harm the users UX by taking longer and showing only a video with a few frames per second.
But anywhere, it's there as a usable example.
